# Generated by Django 4.2.2 on 2023-06-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloggers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True)),
                ('description', models.CharField(max_length=35)),
                ('likes_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('is_enable', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('photo_main', models.ImageField(upload_to='photos/posts/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/posts/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/posts/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/posts/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/posts/%Y/%m/%d/')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bloggers.bloggermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.postmodel')),
            ],
        ),
    ]
