# Generated by Django 4.2.2 on 2023-06-25 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloggerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_text', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('post_count', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(upload_to='photos/bloggers/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
