# Generated by Django 4.2.2 on 2023-06-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggermodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
