# Generated by Django 4.2.2 on 2023-06-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0002_alter_bloggermodel_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggermodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/bloggers/%Y/%m/%d/'),
        ),
    ]
